# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9571d0bc2640ab42aecc137f8d16f52b974b95729f4efc41753c0b82bfedb26a58b7a164e1575a1df5c305e7d3e15dbbdf423e143cf9743f430fe31996af5aa3

test:
  secret_key_base: 24147937876587d42ee7a3bd2cb8fa6b4930ac9f0e11dee317fd9bbcca2e098c65b6b104c27f6a35e8b5d872c88b98a5abb7894792feb97e6db1f55305673513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
